databases:
  - name: terceros-db
    databaseName: terceros01
    user: terceros_user
    plan: free

services:
  - type: web
    name: terceros-app
    env: docker
    plan: free
    region: ohio # Puedes cambiarlo a frankfurt si prefieres Europa
    envVars:
      # Render injects the internal database URL via sync
      - key: RENDER_DB_URL
        fromDatabase:
          name: terceros-db
          property: connectionString
      - key: RENDER_DB_USER
        fromDatabase:
          name: terceros-db
          property: user
      - key: RENDER_DB_PASSWORD
        fromDatabase:
          name: terceros-db
          property: password
