# Configuración específica para Producción (Render)

# Render provee el puerto dinámicamente a través de la variable de entorno PORT.
# Si no está definida (ej: local), usa el 8080.
server.port=${PORT:8080}

# Render inyecta RENDER_DB_URL, RENDER_DB_USER, y RENDER_DB_PASSWORD 
# cuando conectamos la base de datos a través de render.yaml.
spring.datasource.url=${RENDER_DB_URL}
spring.datasource.username=${RENDER_DB_USER}
spring.datasource.password=${RENDER_DB_PASSWORD}

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Asegura que las tablas se actualicen automáticamente basándose en las entidades (ideal para entornos de desarrollo/MVP, considera "validate" para prod estricto)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
