spring.application.name=Terceros
server.port=8080
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

# PostgreSQL config

spring.datasource.url=jdbc:postgresql://localhost:5432/terceros01

spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=postgres

spring.datasource.password="..."

 

# JPA config

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true